--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_participants (
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_admin boolean NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.chat_participants OWNER TO postgres;

--
-- Name: chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chats (
    id bigint NOT NULL,
    chat_name character varying(100),
    chat_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    CONSTRAINT chats_chat_type_check CHECK (((chat_type)::text = ANY (ARRAY[('PRIVATE'::character varying)::text, ('GROUP'::character varying)::text])))
);


ALTER TABLE public.chats OWNER TO postgres;

--
-- Name: chats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    filename character varying(255),
    size_bytes bigint,
    type character varying(255) NOT NULL,
    uploader_id bigint NOT NULL,
    url text NOT NULL,
    CONSTRAINT media_type_check CHECK (((type)::text = ANY (ARRAY[('IMAGE'::character varying)::text, ('FILE'::character varying)::text])))
);


ALTER TABLE public.media OWNER TO postgres;

--
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_statuses (
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT message_statuses_status_check CHECK (((status)::text = ANY (ARRAY[('SENT'::character varying)::text, ('DELIVERED'::character varying)::text, ('SEEN'::character varying)::text])))
);


ALTER TABLE public.message_statuses OWNER TO postgres;

--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    is_revoked boolean NOT NULL,
    media_id bigint,
    reply_to_id bigint,
    revoked_at timestamp(6) without time zone,
    sender_id bigint NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT messages_type_check CHECK (((type)::text = ANY (ARRAY[('TEXT'::character varying)::text, ('IMAGE'::character varying)::text, ('FILE'::character varying)::text])))
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url text,
    created_at timestamp(6) without time zone NOT NULL,
    display_name character varying(50),
    email character varying(100) NOT NULL,
    last_active_at timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    phone character varying(10) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    username character varying(30) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ADMIN'::character varying)::text]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('BANNED'::character varying)::text])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: chat_participants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_participants (chat_id, user_id, is_admin, joined_at) FROM stdin;
\.


--
-- Data for Name: chats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chats (id, chat_name, chat_type, created_at, created_by) FROM stdin;
\.


--
-- Data for Name: media; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.media (id, created_at, filename, size_bytes, type, uploader_id, url) FROM stdin;
\.


--
-- Data for Name: message_statuses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.message_statuses (message_id, user_id, status, updated_at) FROM stdin;
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, chat_id, content, created_at, is_revoked, media_id, reply_to_id, revoked_at, sender_id, type) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, avatar_url, created_at, display_name, email, last_active_at, password_hash, phone, role, status, username) FROM stdin;
2	https://picsum.photos/id/237/200/300	2025-04-22 17:47:55.466392	Default Display Name	longgd@example.com	\N	$2a$10$DqcxxENSoVW/A.ZivOaFr.jNIQlu.eIP8WyI.qcZbrRV/sYkCjhky	0901234567	USER	ACTIVE	longgd
3	https://picsum.photos/id/237/200/300	2025-04-22 17:49:36.286229	Default Display Name	trang@example.com	\N	$2a$10$gfEKjRPcp87Ep4VCnzJHEeLBgwegcsQhWmJVxNqrm283iq.uztlOi	0911223344	USER	ACTIVE	trangnguyen
4	https://picsum.photos/id/237/200/300	2025-04-22 17:50:01.431368	Default Display Name	vinh.tran@example.com	\N	$2a$10$v/8hyli9TeJ6jTGRAH.BDuA6X7ka1sMipkahGhAKkrVHyid8bX6ie	0933445566	USER	ACTIVE	vinhtran
5	https://picsum.photos/id/237/200/300	2025-04-22 17:50:26.358942	Default Display Name	hoangminh@example.com	\N	$2a$10$ZAH.m5f6p23r7gsWVqCahO/uM6y5n7j20pSmQvI245VuUKMxD28na	0977001122	USER	ACTIVE	hoangminh
6	https://picsum.photos/id/237/200/300	2025-04-23 15:03:51.9821	Default Display Name	hahah@example.com	\N	$2a$10$XCoPyqEd9HxOGJmx8x3A..71jkxz5/j0ZkoZXWF/YNNprCRbi4saq	0977001120	USER	ACTIVE	huhu
7	https://picsum.photos/id/237/200/300	2025-04-23 15:41:41.783829	Default Display Name	meo@example.com	\N	$2a$10$M2WXcgkgEfCW581PaGwDJO4m.Ujmy23mYUrZFlrM8xcYrFKX8/TJa	0912345678	USER	ACTIVE	meomeo123
8	https://picsum.photos/id/237/200/300	2025-04-23 15:41:51.275122	Default Display Name	john@example.com	\N	$2a$10$tZ1U1W3/XXnK/guslbvt8eQG77UPjDgu5Wdp1HL7MZVKhXJz5Zsz2	0988111222	USER	ACTIVE	john_doe
9	https://picsum.photos/id/237/200/300	2025-04-23 15:42:00.255308	Default Display Name	sunny@example.com	\N	$2a$10$0kH8OxzPG9dMNfgcfQHDzeT2Zge9a4GaKd8FmdnrE51ClIwb53cXO	0909090909	USER	ACTIVE	sunshine
10	https://picsum.photos/id/237/200/300	2025-04-23 15:42:22.789643	Default Display Name	owl@example.com	\N	$2a$10$YuMFiv.FPw/m1egT.7sFW.CERiudzJsV3/crFwUL3zciuUiwiyf16	0933444555	USER	ACTIVE	nightowl
11	https://picsum.photos/id/237/200/300	2025-04-25 15:53:00.077151	Default Display Name	sunrise1188@example.com	\N	$2a$10$cc5gVM008G0.PeJxa8u02.gaNVM62YU7Y5eZ28kQG/ejxUmrV6ody	0911342333	USER	ACTIVE	sunris1288
12	https://picsum.photos/id/237/200/300	2025-04-25 15:53:41.371074	Default Display Name	sunre1188@example.com	\N	$2a$10$CVlfpQF/HnAVY1CR4rVVUeAfKdmnLgCSdt.IL1SPBieZZf7BkOjAm	0924342333	USER	ACTIVE	sun1288
13	https://picsum.photos/id/237/200/300	2025-04-25 15:54:05.874168	Default Display Name	sunr188@example.com	\N	$2a$10$H7lnqWL72CqklSl7mWeUAegJ78SRre.KxAknaYUeASYkd1TFNwXaK	0924348583	USER	ACTIVE	tungtungtungsahur1288
\.


--
-- Name: chats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chats_id_seq', 1, false);


--
-- Name: media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.media_id_seq', 1, false);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 13, true);


--
-- Name: chat_participants chat_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT chat_participants_pkey PRIMARY KEY (chat_id, user_id);


--
-- Name: chats chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);


--
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- Name: message_statuses message_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_statuses
    ADD CONSTRAINT message_statuses_pkey PRIMARY KEY (message_id, user_id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

