--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_participants (
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_admin boolean NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.chat_participants OWNER TO postgres;

--
-- Name: group_chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_chats (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.group_chats OWNER TO postgres;

--
-- Name: group_chats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    filename character varying(255),
    size_bytes bigint,
    type character varying(255) NOT NULL,
    uploader_id bigint NOT NULL,
    url text NOT NULL,
    CONSTRAINT media_type_check CHECK (((type)::text = ANY (ARRAY[('IMAGE'::character varying)::text, ('FILE'::character varying)::text])))
);


ALTER TABLE public.media OWNER TO postgres;

--
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_statuses (
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT message_statuses_status_check CHECK (((status)::text = ANY (ARRAY[('SENT'::character varying)::text, ('DELIVERED'::character varying)::text, ('SEEN'::character varying)::text])))
);


ALTER TABLE public.message_statuses OWNER TO postgres;

--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    is_revoked boolean NOT NULL,
    media_id bigint,
    reply_to_id bigint,
    revoked_at timestamp(6) without time zone,
    sender_id bigint NOT NULL,
    type character varying(255) NOT NULL,
    group_chat_id bigint,
    private_chat_id bigint,
    CONSTRAINT messages_type_check CHECK (((type)::text = ANY (ARRAY[('TEXT'::character varying)::text, ('IMAGE'::character varying)::text, ('FILE'::character varying)::text])))
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: private_chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.private_chats (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    user1_id bigint NOT NULL,
    user2_id bigint NOT NULL
);


ALTER TABLE public.private_chats OWNER TO postgres;

--
-- Name: private_chats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.private_chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.private_chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url text,
    created_at timestamp(6) without time zone NOT NULL,
    display_name character varying(50),
    email character varying(100) NOT NULL,
    last_active_at timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    phone character varying(10) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    username character varying(30) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ADMIN'::character varying)::text]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('BANNED'::character varying)::text])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: chat_participants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_participants (chat_id, user_id, is_admin, joined_at) FROM stdin;
\.


--
-- Data for Name: group_chats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.group_chats (id, created_at, created_by, name) FROM stdin;
\.


--
-- Data for Name: media; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.media (id, created_at, filename, size_bytes, type, uploader_id, url) FROM stdin;
\.


--
-- Data for Name: message_statuses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.message_statuses (message_id, user_id, status, updated_at) FROM stdin;
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, chat_id, content, created_at, is_revoked, media_id, reply_to_id, revoked_at, sender_id, type, group_chat_id, private_chat_id) FROM stdin;
\.


--
-- Data for Name: private_chats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.private_chats (id, created_at, user1_id, user2_id) FROM stdin;
1	2025-05-08 06:46:27.561286	2	3
2	2025-05-08 06:59:37.344749	2	4
3	2025-05-08 06:59:51.306159	2	5
4	2025-05-08 07:00:04.071227	2	6
5	2025-05-08 07:00:09.715012	2	7
6	2025-05-08 07:00:20.203902	2	8
7	2025-05-08 07:00:25.903963	2	13
8	2025-05-08 07:00:33.676163	2	16
9	2025-05-08 07:00:38.77632	2	17
10	2025-05-08 07:00:55.770718	3	13
11	2025-05-08 07:01:01.147378	3	12
12	2025-05-08 07:01:05.553248	3	11
13	2025-05-08 07:01:11.850588	3	10
14	2025-05-08 07:01:20.974709	3	4
15	2025-05-08 07:01:26.293484	3	5
16	2025-05-08 07:01:32.199316	3	3
17	2025-05-08 07:01:37.177149	3	9
18	2025-05-08 07:01:44.291145	3	7
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, avatar_url, created_at, display_name, email, last_active_at, password_hash, phone, role, status, username) FROM stdin;
2	https://picsum.photos/id/237/200/300	2025-04-22 17:47:55.466392	Phùng Lưu Hoàng Long	longgd@example.com	\N	$2a$10$DqcxxENSoVW/A.ZivOaFr.jNIQlu.eIP8WyI.qcZbrRV/sYkCjhky	0901234567	USER	ACTIVE	longgd
3	https://picsum.photos/id/10/200/300	2025-04-22 17:49:36.286229	Trang Nguyễn	trang@example.com	\N	$2a$10$gfEKjRPcp87Ep4VCnzJHEeLBgwegcsQhWmJVxNqrm283iq.uztlOi	0911223344	USER	ACTIVE	trangnguyen
4	https://picsum.photos/id/11/200/300	2025-04-22 17:50:01.431368	Vinh Trần	vinh.tran@example.com	\N	$2a$10$v/8hyli9TeJ6jTGRAH.BDuA6X7ka1sMipkahGhAKkrVHyid8bX6ie	0933445566	USER	ACTIVE	vinhtran
5	https://picsum.photos/id/12/200/300	2025-04-22 17:50:26.358942	Hoàng Minh	hoangminh@example.com	\N	$2a$10$ZAH.m5f6p23r7gsWVqCahO/uM6y5n7j20pSmQvI245VuUKMxD28na	0977001122	USER	ACTIVE	hoangminh
6	https://picsum.photos/id/13/200/300	2025-04-23 15:03:51.9821	Huhu	hahah@example.com	\N	$2a$10$XCoPyqEd9HxOGJmx8x3A..71jkxz5/j0ZkoZXWF/YNNprCRbi4saq	0977001120	USER	ACTIVE	huhu
7	https://picsum.photos/id/14/200/300	2025-04-23 15:41:41.783829	Meo Meo	meo@example.com	\N	$2a$10$M2WXcgkgEfCW581PaGwDJO4m.Ujmy23mYUrZFlrM8xcYrFKX8/TJa	0912345678	USER	ACTIVE	meomeo123
8	https://picsum.photos/id/15/200/300	2025-04-23 15:41:51.275122	John Doe	john@example.com	\N	$2a$10$tZ1U1W3/XXnK/guslbvt8eQG77UPjDgu5Wdp1HL7MZVKhXJz5Zsz2	0988111222	USER	ACTIVE	john_doe
9	https://picsum.photos/id/16/200/300	2025-04-23 15:42:00.255308	Sunshine	sunny@example.com	\N	$2a$10$0kH8OxzPG9dMNfgcfQHDzeT2Zge9a4GaKd8FmdnrE51ClIwb53cXO	0909090909	USER	ACTIVE	sunshine
10	https://picsum.photos/id/17/200/300	2025-04-23 15:42:22.789643	Night Owl	owl@example.com	\N	$2a$10$YuMFiv.FPw/m1egT.7sFW.CERiudzJsV3/crFwUL3zciuUiwiyf16	0933444555	USER	ACTIVE	nightowl
11	https://picsum.photos/id/18/200/300	2025-04-25 15:53:00.077151	Sunrise	sunrise1188@example.com	\N	$2a$10$cc5gVM008G0.PeJxa8u02.gaNVM62YU7Y5eZ28kQG/ejxUmrV6ody	0911342333	USER	ACTIVE	sunris1288
12	https://picsum.photos/id/19/200/300	2025-04-25 15:53:41.371074	Sun	sunre1188@example.com	\N	$2a$10$CVlfpQF/HnAVY1CR4rVVUeAfKdmnLgCSdt.IL1SPBieZZf7BkOjAm	0924342333	USER	ACTIVE	sun1288
13	https://picsum.photos/id/20/200/300	2025-04-25 15:54:05.874168	Tung Tung Tung Sahur	sunr188@example.com	\N	$2a$10$H7lnqWL72CqklSl7mWeUAegJ78SRre.KxAknaYUeASYkd1TFNwXaK	0924348583	USER	ACTIVE	tungtungtungsahur1288
16	https://picsum.photos/id/21/200/300	2025-04-25 19:04:25.233595	Tui La Gay	gay@example.com	\N	$2a$10$ooylX9JrObH1LP0uLtE2wOYDpbccxF   CrCYiwCvIEO7//RfDJfKt2O	9093456699	USER	ACTIVE	tuiLaGay
17	https://picsum.photos/id/22/200/300	2025-04-25 19:09:20.107165	Vitamin D	VitaminD@example.com	\N	$2a$10$PzQb7OrhWVSEg8hsYOteoOtHZIQ3DEZcL4RbcRbVOtrkeY5/UUMTG	9093432399	USER	ACTIVE	VitaminD
19	https://picsum.photos/id/23/200/300	2025-04-25 19:09:39.919344	Con Meo	Meowwww@example.com	\N	$2a$10$eNitChimr6UGax7Pmp/Kr.N.BadWwjJKj2Wts2fS.z5DbKxNUAu8.	9093442399	USER	ACTIVE	Meowwww
\.


--
-- Name: group_chats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.group_chats_id_seq', 1, false);


--
-- Name: media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.media_id_seq', 1, false);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 1, false);


--
-- Name: private_chats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.private_chats_id_seq', 18, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 19, true);


--
-- Name: chat_participants chat_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT chat_participants_pkey PRIMARY KEY (chat_id, user_id);


--
-- Name: group_chats group_chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_chats
    ADD CONSTRAINT group_chats_pkey PRIMARY KEY (id);


--
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- Name: message_statuses message_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_statuses
    ADD CONSTRAINT message_statuses_pkey PRIMARY KEY (message_id, user_id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: private_chats private_chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.private_chats
    ADD CONSTRAINT private_chats_pkey PRIMARY KEY (id);


--
-- Name: private_chats uk42kce6db202frphgynl0p3fg7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.private_chats
    ADD CONSTRAINT uk42kce6db202frphgynl0p3fg7 UNIQUE (user1_id, user2_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_chat_participants_chat_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_participants_chat_user ON public.chat_participants USING btree (chat_id, user_id);


--
-- Name: idx_chat_participants_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_participants_user ON public.chat_participants USING btree (user_id);


--
-- Name: idx_messages_chat_createdat; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_messages_chat_createdat ON public.messages USING btree (chat_id, created_at DESC);


--
-- Name: idx_messages_sender; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_messages_sender ON public.messages USING btree (sender_id);


--
-- PostgreSQL database dump complete
--

